export interface RecommendationType {
    image: string
    name: string
    designation: string
    recommendation: string
}

export const recommendations: RecommendationType[] = [
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
    {
        image: 'https://media.licdn.com/dms/image/v2/D4D03AQFb7c3q4xLVDQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726566094951?e=1746662400&v=beta&t=L-qjDxttw3YtQgf75KJ6Wv-jjYRlnlW-3Z7n1WExRQI',
        name: 'Shaz Saleem',
        designation: 'Integration Architect at Kyte Consulting | Oracle Certified Integration Expert',
        recommendation: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi accumsan mattis lobortis. Pellentesque a feugiat tellus. Nunc quis lacinia sapien. Morbi bibendum erat nec lectus fermentum pellentesque. Fusce porttitor interdum convallis. In at diam at erat dignissim dignissim nec at dolor. Nunc et imperdiet ante, vitae euismod eros. Praesent porttitor elementum ante, eu vulputate velit. Ut elementum magna justo, sit amet imperdiet odio eleifend eget.

Duis tempus ex justo, sed mattis neque pellentesque rhoncus. Nullam convallis varius varius. Fusce vel neque sed tellus blandit maximus sit amet non odio. Vivamus ac vehicula risus. Quisque mattis aliquet vehicula. Maecenas quis ligula molestie, semper tellus ac, cursus nisl. Nunc ut vehicula justo. Proin dignissim pretium leo, ut tincidunt eros vestibulum ac. Integer eleifend consequat dui, sed gravida magna tristique id. Maecenas pharetra justo purus, at aliquam mauris facilisis vitae. Vivamus accumsan tincidunt purus. In id nunc tellus. Pellentesque eleifend nisl sit amet purus vulputate, eu gravida nibh laoreet. Aenean nec blandit mi.

Nullam mauris magna, finibus posuere purus sed, aliquet tristique purus. Donec convallis ex nec euismod hendrerit. In hac habitasse platea dictumst. Cras sed euismod dui. Curabitur tempus, nunc eu blandit laoreet, nulla mauris sodales ante, facilisis consequat diam augue a sem. Aenean vitae lacus ac purus commodo condimentum. Sed gravida lacinia interdum.

Phasellus efficitur, sem et blandit euismod, est nisl consequat tellus, quis hendrerit urna ipsum eu nibh. Nulla eu rutrum tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse aliquet tortor quis libero hendrerit condimentum. Ut molestie ipsum sed eros egestas molestie. Morbi diam lorem, elementum eget condimentum id, varius ut erat. Cras sed maximus sem. Cras neque felis, feugiat vitae nunc ut, mollis suscipit ex. Proin non magna mauris. Sed eget elit tincidunt, dapibus ex vel, lobortis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere metus vel felis lacinia, vel dictum diam consequat.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam at auctor sem, in aliquam ligula. Curabitur eu imperdiet turpis. Praesent malesuada ex eu lacus rhoncus, id dictum nulla egestas. Proin sollicitudin malesuada risus, nec dictum augue luctus vel. Vivamus luctus diam at neque rhoncus interdum. Quisque neque diam, iaculis quis sem sit amet, maximus viverra orci. Aenean justo ante, vulputate at volutpat ac, mollis a orci. Ut leo tortor, eleifend sit amet laoreet nec, ultricies sed mi. Mauris condimentum erat bibendum blandit molestie. Fusce et mauris quam.`
    },
]